## Introduction : Pourquoi le nettoyage des données est fondamental

Dans tout projet de data science, d’économétrie ou de suivi-évaluation, la qualité des résultats dépend avant tout de la qualité des données utilisées. 

Or, dans la réalité, les données sont rarement propres : elles contiennent des valeurs manquantes, des erreurs de saisie, des doublons, des incohérences ou des formats inadaptés.

Le nettoyage de données avec Pandas (bibliothèque Python) est une étape incontournable. Il permet de transformer des données brutes en un jeu de données fiable, cohérent et exploitable pour l’analyse et la modélisation.

### 1. Enjeux stratégiques du nettoyage des données

Le data cleaning (ou data wrangling) n’est pas une tâche subalterne : c’est un levier stratégique.
Règle empirique : Un bon modèle sur de mauvaises données reste un mauvais modèle.

**Objectifs principaux**
- Garantir la qualité des analyses : des données propres évitent des conclusions erronées.

- Assurer la fiabilité des modèles prédictifs : un modèle entraîné sur des données bruitées généralisera mal.

- Réduire les biais statistiques : les valeurs manquantes ou aberrantes peuvent fausser les estimations.

- Faciliter la prise de décision : des données cohérentes renforcent la confiance des parties prenantes.

**Exemple concret**

Imaginez une enquête sur le revenu des ménages. Si 10 % des revenus sont saisis comme « -999 » (code pour « refus ») et que vous ne les nettoyez pas, la moyenne des revenus sera artificiellement basse. Un modèle prédisant le pouvoir d’achat sera donc inutilisable.

### 2. Audit initial des données (Data Profiling)

Avant toute transformation, il faut comprendre profondément le jeu de données. L’audit permet d’identifier les problèmes potentiels.

In [26]:
import pandas as pd
import numpy as np

data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 3, 14, 15],  # Doublon d'ID
    
    'Nom': ['Alice', 'bob', 'CHARLIE', '  David  ', 'Eve', 'Frank', 
            'Grace', None, 'Ivy', 'Jack', 'Alice', 'Léo', 'Mia', '???', 'Nina'],
    
    'Âge': [25, 30, -5, 150, 28, 'trente', None, 42, 0, 35, 25, np.nan, 29, 31, 999],
    
    'Genre': ['F', 'M', 'Masculin', 'H', 'Femme', 'M', 'f', None, 'X', 'M', 'F', 'Male', 'F', 'Inconnu', 'F'],
    
    'Email': ['alice@email.com', 'bob_email.com', 'charlie@email', 'DAVID@EMAIL.COM', 
              'eve@email.com', None, 'grace@email.com', 'henry@email.com', 'n/a', 
              'jack@email.com', 'alice@email.com', '', 'mia@email.com', 'N/A', 'nina@email.com'],
    
    'Téléphone': ['0612345678', '06 12 34 56 79', '+33612345680', '612345681', 
                  'abcdefghij', None, '06.12.34.56.82', '0033612345683', '0000000000',
                  '0612345684', '0612345678', np.nan, '06-12-34-56-85', 'NA', '0612345686'],
    
    'Ville': ['Paris', 'paris', 'LYON', 'Lyon ', ' Marseille', 'Toulouse', 
              'toulouse', None, 'N/A', 'Bordeaux', 'Paris', '', 'Nice', 'Unknown', 'Lille'],
    
    'Code_Postal': ['75001', '69001', '13001', '31000', '75002', '31001', 
                    '6900A', None, '-1', '33000', '75001', 'XXXXX', '06000', '99999', '59000'],
    
    'Revenu': [50000, 60000, -5000, 55000, 999999999, 70000, 65000, None, 
               0, 72000, 50000, 'cinquante mille', 48000, np.nan, 62000],
    
    'Date_Naissance': ['1998-05-15', '15/03/1993', '1988-13-45', 'March 5, 1990', 
                       '01-01-1995', None, '2050-01-01', '1985-07-20', 'N/A',
                       '1988/06/10', '1998-05-15', '', '1994-11-30', '0000-00-00', '1991-09-25'],
    
    'Date_Inscription': ['2020-01-15', '2020-01-15', '2019-06-20', '2021-03-10', 
                         '2018-12-01', '2022-07-25', '2023-02-14', '2017-09-30',
                         '2024-05-05', '2016-11-11', '2020-01-15', '2025-08-20',
                         '2021-04-18', '2019-01-01', '2020-06-30'],
    
    'Statut': ['Actif', 'actif', 'INACTIF', 'Pending', 'actif ', None, 
               'Active', 'Inactive', '1', '0', 'Actif', 'oui', 'non', 'N/A', 'Actif'],
    
    'Score': [85.5, 90.0, 78.3, 105.0, -10.0, 88.8, None, 92.1, np.inf, 
              76.4, 85.5, 'Excellent', 81.2, np.nan, 79.9],
    
    'Commentaire': ['RAS', '  ', 'Bon client', None, 'Client fidèle depuis 5 ans!!!', 
                    '<script>alert("hack")</script>', 'OK', '   Très bien   ', 
                    'NULL', 'Client premium\nMulti-ligne', 'RAS', '\t\t', 
                    'Satisfait', 'nan', ''],
    
    'Montant_Achat': ['1500.50', '2000', '1,234.56', '€3000', '2500.00€', 
                      None, '1800.75', 'mille', '-500', '2200.00', '1500.50',
                      '3,500', '1950.25', 'N/A', '2100.00']
}

df = pd.DataFrame(data)
df

,ID,Nom,Âge,Genre,Email,Téléphone,Ville,Code_Postal,Revenu,Date_Naissance,Date_Inscription,Statut,Score,Commentaire,Montant_Achat
0,1,Alice,25,F,alice@email.com,0612345678,Paris,75001,50000,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50
1,2,bob,30,M,bob_email.com,06 12 34 56 79,paris,69001,60000,15/03/1993,2020-01-15,actif,90.0,,2000
2,3,CHARLIE,-5,Masculin,charlie@email,+33612345680,LYON,13001,-5000,1988-13-45,2019-06-20,INACTIF,78.3,Bon client,"1,234.56"
3,4,David,150,H,DAVID@EMAIL.COM,612345681,Lyon,31000,55000,"March 5, 1990",2021-03-10,Pending,105.0,NaN,€3000
4,5,Eve,28,Femme,eve@email.com,abcdefghij,Marseille,75002,999999999,01-01-1995,2018-12-01,actif,-10.0,Client fidèle depuis 5 ans!!!,2500.00€
5,6,Frank,trente,M,NaN,NaN,Toulouse,31001,70000,NaN,2022-07-25,NaN,88.8,"<script>alert(""hack"")</script>",NaN
6,7,Grace,None,f,grace@email.com,06.12.34.56.82,toulouse,6900A,65000,2050-01-01,2023-02-14,Active,None,OK,1800.75
7,8,NaN,42,NaN,henry@email.com,0033612345683,NaN,NaN,None,1985-07-20,2017-09-30,Inactive,92.1,Très bien,mille
8,9,Ivy,0,X,n/a,0000000000,N/A,-1,0,N/A,2024-05-05,1,inf,NULL,-500
9,10,Jack,35,M,jack@email.com,0612345684,Bordeaux,33000,72000,1988/06/10,2016-11-11,0,76.4,Client premium\nMulti-ligne,2200.00
10,11,Alice,25,F,alice@email.com,0612345678,Paris,75001,50000,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50
11,12,Léo,NaN,Male,,NaN,,XXXXX,cinquante mille,,2025-08-20,oui,Excellent,\t\t,"3,500"
12,3,Mia,29,F,mia@email.com,06-12-34-56-85,Nice,06000,48000,1994-11-30,2021-04-18,non,81.2,Satisfait,1950.25
13,14,???,31,Inconnu,N/A,NA,Unknown,99999,NaN,0000-00-00,2019-01-01,N/A,NaN,nan,N/A
14,15,Nina,999,F,nina@email.com,0612345686,Lille,59000,62000,1991-09-25,2020-06-30,Actif,79.9,,2100.00

**Points à analyser**

- Types de variables : **numériques** (int, float), **catégorielles** (object, category), **dates** (datetime).

- Proportion de valeurs manquantes par colonne.

- Distribution des variables (moyenne, écart-type, quantiles).

- Présence d’anomalies visibles (ex. âge = 999, date = « 31/02/2020 »).

**Liste des anomalies présentes dans notre data frame**


**Catégorie**	        ---------    **Exemples dans le DataFrame**

- *Valeurs manquantes* :	None, np.nan, chaînes vides '', 'N/A', 'n/a', 'NULL', 'nan'

- *Doublons*	:     Lignes 0 et 10 identiques, ID 3 en double

- *Incohérence de casse* : 	'bob' vs 'CHARLIE' vs 'Alice'

- *Espaces parasites* : ' David ', 'Lyon ', ' Marseille'

-   *Formats incohérents* : 	Dates en 3 formats, téléphones variés

-   *Valeurs aberrantes*  : 	Âge -5, 150, 999 ; Revenu négatif ou 999999999

-   *Types incorrects*	: Âge 'trente', Revenu 'cinquante mille'

- *Catégories non standardisées*  : 	Genre : 'F', 'Femme', 'f', 'Female'

-   *Valeurs impossibles*	:  Date '1988-13-45', Score > 100, np.inf

-   *Données futures invalides* : 	Date de naissance en 2050

-   *Injection/caractères spéciaux* : 	Balise HTML dans Commentaire

-   *Symboles dans les nombres*  : 	'€3000', '2500.00€', '1,234.56'

-   *Emails invalides*  : 	Sans @, domaine incomplet

**Astuce pro** : rapport automatisé

Utilisez *ydata-profiling* (ex-pandas-profiling) pour générer un rapport HTML interactif.

In [ ]:
from ydata_profiling import ProfileReport       # pip install ydata-profiling
profile = ProfileReport(df, title="Rapport d'audit")
profile.to_file("audit.html")

**Exemple concret**

Vous chargez une base de 100 000 clients. *df.info()* révèle que la colonne « date_naissance » est de type *object* (texte) au lieu de *datetime*. C’est un problème à corriger. De plus, « revenu » a 15 % de valeurs manquantes.

### 3. Gestion avancée des valeurs manquantes

Les valeurs manquantes ne doivent pas être traitées mécaniquement. Leur origine détermine la stratégie.

#### Typologie des données manquantes

- **MCAR** (Missing Completely At Random) : l’absence ne dépend d’aucune variable (ex. panne serveur). Suppression ou imputation simple acceptable.

- **MAR** (Missing At Random) : l’absence dépend d’autres variables observées (ex. les hommes déclarent moins leur revenu). Il faut imputer en utilisant ces variables.

- **MNAR** (Missing Not At Random) : l’absence est liée à la valeur elle-même (ex. les très hauts revenus ne sont pas déclarés). Nécessite une modélisation spécifique ou des données externes.

# ______________________________________________________________

### 🧩 Étapes du nettoyage prévues

**1- Exploration générale du DataFrame** :

- Aperçu des types, valeurs uniques, nulls, doublons, etc.

**2 - Gestion des valeurs manquantes** :
-   Identifier les valeurs manquantes sous toutes leurs formes (None, NaN, 'nan', 'N/A', etc.)
-   Les remplacer ou supprimer selon la colonne.

**3- Nettoyage des chaînes de caractères** :
-   Supprimer espaces, uniformiser la casse, retirer caractères parasites ou HTML.

**4 - Correction des types de données** :
-   Convertir les colonnes (Âge, Revenu, Montant_Achat, Score, Dates, …) dans un type cohérent.

**5 - Traitement des valeurs aberrantes (outliers)** :
- Détecter et analyser les valeurs extrêmes selon la logique métier.

**6 - Standardisation des catégories** :
-   Harmoniser les libellés pour Genre, Statut, Ville, etc.

**7 - Nettoyage de formats spécifiques** :
-   Dates, numéros de téléphone, emails, montants en euro.

**8 - Suppression / gestion des doublons.**

**9 - Vérifications finales et DataFrame propre 🚀**

### 🔍 Étape 1 : Exploration initiale

Voici le code pour bien comprendre notre jeu de données :

In [27]:
# Info générale
print("=== INFO GÉNÉRALE ===")
print(df.info())

=== INFO GÉNÉRALE ===
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                15 non-null     int64
 1   Nom               14 non-null     str
 2   Âge               13 non-null     object
 3   Genre             14 non-null     str
 4   Email             14 non-null     str
 5   Téléphone         13 non-null     str
 6   Ville             14 non-null     str
 7   Code_Postal       14 non-null     str
 8   Revenu            13 non-null     object
 9   Date_Naissance    14 non-null     str
 10  Date_Inscription  15 non-null     str
 11  Statut            14 non-null     str
 12  Score             13 non-null     object
 13  Commentaire       14 non-null     str
 14  Montant_Achat     14 non-null     str
dtypes: int64(1), object(3), str(11)
memory usage: 1.9+ KB
None

In [28]:
# Valeurs manquantes brutes
print("\n=== NOMBRE DE MISSINGS ===")
print(df.isna().sum())

=== NOMBRE DE MISSINGS ===
ID                  0
Nom                 1
Âge                 2
Genre               1
Email               1
Téléphone           2
Ville               1
Code_Postal         1
Revenu              2
Date_Naissance      1
Date_Inscription    0
Statut              1
Score               2
Commentaire         1
Montant_Achat       1
dtype: int64

In [32]:
# Aperçu rapide
print("\n=== PREMIÈRES LIGNES ===")
df.head()

=== PREMIÈRES LIGNES ===

,ID,Nom,Âge,Genre,Email,Téléphone,Ville,Code_Postal,Revenu,Date_Naissance,Date_Inscription,Statut,Score,Commentaire,Montant_Achat
0,1,Alice,25,F,alice@email.com,0612345678,Paris,75001,50000,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50
1,2,bob,30,M,bob_email.com,06 12 34 56 79,paris,69001,60000,15/03/1993,2020-01-15,actif,90.0,,2000
2,3,CHARLIE,-5,Masculin,charlie@email,+33612345680,LYON,13001,-5000,1988-13-45,2019-06-20,INACTIF,78.3,Bon client,"1,234.56"
3,4,David,150,H,DAVID@EMAIL.COM,612345681,Lyon,31000,55000,"March 5, 1990",2021-03-10,Pending,105.0,NaN,€3000
4,5,Eve,28,Femme,eve@email.com,abcdefghij,Marseille,75002,999999999,01-01-1995,2018-12-01,actif,-10.0,Client fidèle depuis 5 ans!!!,2500.00€

In [34]:
# Valeurs uniques par colonne (pour détecter anomalies)
print("\n=== VALEURS UNIQUES PAR COLONNE ===")
for col in df.columns:
    uniques = df[col].unique()
    print(f"{col}: {len(uniques)} valeurs uniques -> {uniques[:10]}")  # on limite l'affichage
    print()

=== VALEURS UNIQUES PAR COLONNE ===
ID: 14 valeurs uniques -> [ 1  2  3  4  5  6  7  8  9 10]

Nom: 14 valeurs uniques -> <StringArray>
[    'Alice',       'bob',   'CHARLIE', '  David  ',       'Eve',     'Frank',
     'Grace',         nan,       'Ivy',      'Jack']
Length: 10, dtype: str

Âge: 14 valeurs uniques -> [25 30 -5 150 28 'trente' None 42 0 35]

Genre: 10 valeurs uniques -> <StringArray>
['F', 'M', 'Masculin', 'H', 'Femme', 'f', nan, 'X', 'Male', 'Inconnu']
Length: 10, dtype: str

Email: 14 valeurs uniques -> <StringArray>
['alice@email.com',   'bob_email.com',   'charlie@email', 'DAVID@EMAIL.COM',
   'eve@email.com',               nan, 'grace@email.com', 'henry@email.com',
             'n/a',  'jack@email.com']
Length: 10, dtype: str

Téléphone: 13 valeurs uniques -> <StringArray>
[    '0612345678', '06 12 34 56 79',   '+33612345680',      '612345681',
     'abcdefghij',              nan, '06.12.34.56.82',  '0033612345683',
     '0000000000',     '0612345684']
Length: 10, dtype: str

Ville: 14 valeurs uniques -> <StringArray>
[     'Paris',      'paris',       'LYON',      'Lyon ', ' Marseille',
   'Toulouse',   'toulouse',          nan,        'N/A',   'Bordeaux']
Length: 10, dtype: str

Code_Postal: 14 valeurs uniques -> <StringArray>
['75001', '69001', '13001', '31000', '75002', '31001', '6900A',     nan,
    '-1', '33000']
Length: 10, dtype: str

Revenu: 14 valeurs uniques -> [50000 60000 -5000 55000 999999999 70000 65000 None 0 72000]

Date_Naissance: 14 valeurs uniques -> <StringArray>
[   '1998-05-15',    '15/03/1993',    '1988-13-45', 'March 5, 1990',
    '01-01-1995',             nan,    '2050-01-01',    '1985-07-20',
           'N/A',    '1988/06/10']
Length: 10, dtype: str

Date_Inscription: 13 valeurs uniques -> <StringArray>
['2020-01-15', '2019-06-20', '2021-03-10', '2018-12-01', '2022-07-25',
 '2023-02-14', '2017-09-30', '2024-05-05', '2016-11-11', '2025-08-20']
Length: 10, dtype: str

Statut: 13 valeurs uniques -> <StringArray>
[   'Actif',    'actif',  'INACTIF',  'Pending',   'actif ',        nan,
   'Active', 'Inactive',        '1',        '0']
Length: 10, dtype: str

Score: 14 valeurs uniques -> [85.5 90.0 78.3 105.0 -10.0 88.8 None 92.1 inf 76.4]

Commentaire: 14 valeurs uniques -> <StringArray>
[                           'RAS',                             '  ',
                     'Bon client',                              nan,
  'Client fidèle depuis 5 ans!!!', '<script>alert("hack")</script>',
                             'OK',                '   Très bien   ',
                           'NULL',    'Client premium\nMulti-ligne']
Length: 10, dtype: str

Montant_Achat: 14 valeurs uniques -> <StringArray>
[ '1500.50',     '2000', '1,234.56',    '€3000', '2500.00€',        nan,
  '1800.75',    'mille',     '-500',  '2200.00']
Length: 10, dtype: str

### 🩹 Étape 2 : Gestion des valeurs manquantes

-   1. Identifier toutes les formes de valeurs manquantes

Le problème : les "valeurs manquantes" ne sont pas toujours des *NaN*.
Elles peuvent aussi être représentées par : "*NA*", "*N/A*", "*n/a*", "*nan*", "", "*NULL*", etc.

👉 On commence donc par les convertir en np.nan pour les traiter plus facilement.

In [53]:
# Liste des valeurs à considérer comme "manquantes"
missing_values = ["N/A", "n/a", "NA", "na", "NULL", "null", "Nan", "nan", "", " "]

# Remplacer ces valeurs par np.nan
df.replace(missing_values, np.nan, inplace=True)  # inplace=True modifie le DataFrame original
df.sample(5)

,ID,Nom,Âge,Genre,Email,Téléphone,Ville,Code_Postal,Revenu,Date_Naissance,Date_Inscription,Statut,Score,Commentaire,Montant_Achat
1,2,Bob,30.0,M,bob_email.com,06 12 34 56 79,Paris,69001,60000.0,NaT,2020-01-15,Actif,90.0,NaN,2000
12,3,Mia,29.0,F,mia@email.com,06-12-34-56-85,Nice,06000,48000.0,1994-11-30,2021-04-18,Non,81.2,Satisfait,1950.25
10,11,Alice,25.0,F,alice@email.com,0612345678,Paris,75001,50000.0,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50
5,6,Frank,NaN,M,Inconnu,Inconnu,Toulouse,31001,70000.0,NaT,2022-07-25,Inconnu,88.8,"<script>alert(""hack"")</script>",NaN
6,7,Grace,NaN,F,grace@email.com,06.12.34.56.82,Toulouse,6900A,65000.0,2050-01-01,2023-02-14,Active,NaN,OK,1800.75

-   2. Vérifier combien de valeurs manquantes par colonne

In [43]:
print(df.isna().sum().sort_values(ascending=False))

Email               4
Commentaire         4
Téléphone           3
Date_Naissance      3
Ville               3
Âge                 2
Statut              2
Score               2
Montant_Achat       2
Revenu              2
Nom                 1
Code_Postal         1
Genre               1
ID                  0
Date_Inscription    0
dtype: int64

Cela nous montre les colonnes les plus concernées (Commentaire, Email, Ville, etc.)

In [ ]:
# Pourcentage trié des valeurs manquantes 
(df.isna().mean() * 100).sort_values(ascending=False)

Email               26.666667
Commentaire         26.666667
Téléphone           20.000000
Date_Naissance      20.000000
Ville               20.000000
Âge                 13.333333
Statut              13.333333
Score               13.333333
Montant_Achat       13.333333
Revenu              13.333333
Nom                  6.666667
Code_Postal          6.666667
Genre                6.666667
ID                   0.000000
Date_Inscription     0.000000
dtype: float64

-   3. Décider que faire selon la nature de la colonne

In [ ]:
"""
Type de colonne  	                      Exemples	                                             Traitement typique

Identifiant / clé	                       ID	                 On ne doit jamais avoir de valeurs manquantes -> à vérifier avant suppression.
Texte libre / catégoriel	       Ville, Nom, Genre, Statut	          Remplacer les NaN par 'Inconnu' ou 'Non spécifié' si pertinent.
Valeur numérique	                  Âge, Revenu, Score	                Imputation par moyenne, médiane, ou suppression selon le cas.
Dates	                           Date_Naissance, Date_Inscription	         Remplacer par une date par défaut ou laisser NaT si utile dans l'analyse.
Colonnes peu utiles (trop de NaN)	      ≥ 70-80 % de NaN	                            Suppression de la colonne possible. 

"""

-   4. Application pratique

Voici un traitement raisonnable selon nos données :

In [ ]:
# Remplacement des NaN dans les colonnes catégorielles
colonnes_cat = ['Nom', 'Ville', 'Genre', 'Statut', 'Email', 'Téléphone', 'Commentaire']
df[colonnes_cat] = df[colonnes_cat].fillna('Inconnu')

# Remplacement des NaN numériques (par médiane)
colonnes_num = ['Âge', 'Revenu', 'Score']
for col in colonnes_num:
    df[col] = pd.to_numeric(df[col], errors='coerce')  # conversion préalable
    mediane = df[col].median()
    df[col].fillna(mediane, inplace=True)


# Dates : conversion + remplissage
for col in ['Date_Naissance', 'Date_Inscription']:
    df[col] = pd.to_datetime(df[col], errors='coerce')

-   5. Vérification finale

In [46]:
print("\n=== Missings après traitement ===")
print(df.isna().sum().sort_values(ascending=False))

=== Missings après traitement ===
Date_Naissance      9
Revenu              3
Âge                 3
Score               3
Montant_Achat       2
Code_Postal         1
ID                  0
Ville               0
Téléphone           0
Email               0
Genre               0
Nom                 0
Date_Inscription    0
Statut              0
Commentaire         0
dtype: int64

### 🧼 Étape 3 : Nettoyage des chaînes de caractères

Ici, on veut rendre les colonnes texte propres, uniformes et exploitables.

-   1. Supprimer les espaces inutiles

Beaucoup de chaînes contiennent des espaces ou tabulations en trop (' David ', ' Marseille', etc.).

On va les retirer :

In [ ]:
# Suppression des espaces avant/après pour toutes les colonnes string

df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

# Autres méthodes possibles si df.map() ne fonctionne pas :
# df = df.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))
# df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# isinstance(x, str) vérifie que x est une chaîne de caractères avant d'appliquer strip()

-   2. Harmoniser la casse (majuscules/minuscules)

Pour éviter d’avoir plusieurs variantes ("Paris", "paris", "PARIS"), on passe en minuscule puis on normalise la première lettre.

In [ ]:
colonnes_string = ['Nom', 'Ville', 'Genre', 'Statut']
for col in colonnes_string:
    df[col] = df[col].str.lower().str.title()


# ➡️ paris, PARIS, Paris deviennent tous Paris.

-   3. Suppression des caractères spéciaux et HTML

Certaines cellules (ex. Commentaire) contiennent du contenu non voulu comme du HTML, des balises ou des retours à la ligne.

In [55]:
import re

def nettoyer_texte(txt):
    if isinstance(txt, str):
        # Supprimer tout ce qui ressemble à une balise HTML
        txt = re.sub(r'<.*?>', '', txt)   
        # Remplacer retours à la ligne ou tabulations par un espace simple
        txt = re.sub(r'[\r\n\t]+', ' ', txt)
        # Supprimer espaces consécutifs
        txt = re.sub(' +', ' ', txt)
        return txt.strip()
    return txt

df['Commentaire'] = df['Commentaire'].apply(nettoyer_texte)

-   4. Valeurs non informatives → NaN

(ex. 'Inconnu', '???', 'None', '0' pour des textes)

On remplace ces valeurs génériques par np.nan (pour pouvoir les traiter proprement après).

In [56]:
valeurs_vides = ['Inconnu', '?', '???', 'None', '0']
df.replace(valeurs_vides, np.nan, inplace=True)

,ID,Nom,Âge,Genre,Email,Téléphone,Ville,Code_Postal,Revenu,Date_Naissance,Date_Inscription,Statut,Score,Commentaire,Montant_Achat
0,1,Alice,25.0,F,alice@email.com,0612345678,Paris,75001,50000.0,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50
1,2,Bob,30.0,M,bob_email.com,06 12 34 56 79,Paris,69001,60000.0,NaT,2020-01-15,Actif,90.0,NaN,2000
2,3,Charlie,-5.0,Masculin,charlie@email,+33612345680,Lyon,13001,-5000.0,NaT,2019-06-20,Inactif,78.3,Bon client,"1,234.56"
3,4,David,150.0,H,DAVID@EMAIL.COM,612345681,Lyon,31000,55000.0,NaT,2021-03-10,Pending,105.0,NaN,€3000
4,5,Eve,28.0,Femme,eve@email.com,abcdefghij,Marseille,75002,999999999.0,NaT,2018-12-01,Actif,-10.0,Client fidèle depuis 5 ans!!!,2500.00€
5,6,Frank,NaN,M,NaN,NaN,Toulouse,31001,70000.0,NaT,2022-07-25,NaN,88.8,"alert(""hack"")",NaN
6,7,Grace,NaN,F,grace@email.com,06.12.34.56.82,Toulouse,6900A,65000.0,2050-01-01,2023-02-14,Active,NaN,OK,1800.75
7,8,NaN,42.0,NaN,henry@email.com,0033612345683,NaN,NaN,NaN,1985-07-20,2017-09-30,Inactive,92.1,Très bien,mille
8,9,Ivy,0.0,X,NaN,0000000000,NaN,-1,0.0,NaT,2024-05-05,1,inf,NaN,-500
9,10,Jack,35.0,M,jack@email.com,0612345684,Bordeaux,33000,72000.0,NaT,2016-11-11,NaN,76.4,Client premium Multi-ligne,2200.00
10,11,Alice,25.0,F,alice@email.com,0612345678,Paris,75001,50000.0,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50
11,12,Léo,NaN,Male,NaN,NaN,NaN,XXXXX,NaN,NaT,2025-08-20,Oui,NaN,NaN,"3,500"
12,3,Mia,29.0,F,mia@email.com,06-12-34-56-85,Nice,06000,48000.0,1994-11-30,2021-04-18,Non,81.2,Satisfait,1950.25
13,14,NaN,31.0,NaN,NaN,NaN,Unknown,99999,NaN,NaT,2019-01-01,NaN,NaN,NaN,NaN
14,15,Nina,999.0,F,nina@email.com,0612345686,Lille,59000,62000.0,1991-09-25,2020-06-30,Actif,79.9,NaN,2100.00

-   5. Vérifions le résultat

In [58]:
# Aperçu de quelques colonnes nettoyées
print(df[['Nom', 'Ville', 'Genre', 'Commentaire']].head(10))

"""
On devrait maintenant observer :

plus de majuscules incohérentes,
ni espaces parasites,
ni tags ou caractères bizarres dans les commentaires.

"""

       Nom      Ville     Genre                    Commentaire
0    Alice      Paris         F                            RAS
1      Bob      Paris         M                            NaN
2  Charlie       Lyon  Masculin                     Bon client
3    David       Lyon         H                            NaN
4      Eve  Marseille     Femme  Client fidèle depuis 5 ans!!!
5    Frank   Toulouse         M                  alert("hack")
6    Grace   Toulouse         F                             OK
7      NaN        NaN       NaN                      Très bien
8      Ivy        NaN         X                            NaN
9     Jack   Bordeaux         M     Client premium Multi-ligne

'\nOn devrait maintenant observer :\n\nplus de majuscules incohérentes,\nni espaces parasites,\nni tags ou caractères bizarres dans les commentaires.\n\n'

### 🔢 Étape 4 : Correction des types de données

**L’objectif ici** : que chaque colonne ait le bon type (int, float, datetime, category, etc.),

et que les formats incohérents (ex. 'cinquante mille', '€3000', dates non valides…) soient nettoyés ou convertis.

-   1. Correction des types numériques

Certaines colonnes contiennent des valeurs incorrectes ou sous forme de texte :

*Âge* → nombres négatifs, texte ("trente")

*Revenu* → texte ("cinquante mille"), montants aberrants

*Score* → valeur texte ("Excellent"), np.inf, négatifs, etc.

*Montant_Achat* → séparateurs , ou symboles €

On traite tout cela.

In [59]:
import numpy as np
import pandas as pd
import re

# Conversion sûre en numérique pour Âge, Revenu, Score
for col in ['Âge', 'Revenu', 'Score']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Nettoyage de la colonne Montant_Achat
def nettoyer_montant(val):
    if isinstance(val, str):
        val = val.replace('€', '').replace(',', '.').replace(' ', '')
        val = re.sub('[^0-9.-]', '', val)  # garde seulement chiffres et signe
    return pd.to_numeric(val, errors='coerce')

df['Montant_Achat'] = df['Montant_Achat'].apply(nettoyer_montant)

*errors="coerce"* : les valeurs non convertibles deviennent *NaN* (au lieu de faire planter le script).

Après conversion, il faut à nouveau gérer les *NaN* créés.

-   2. Correction des valeurs aberrantes numériques

On fixe des bornes logiques :

In [60]:
# Pour Âge
df.loc[(df['Âge'] < 0) | (df['Âge'] > 120), 'Âge'] = np.nan

# Pour Revenu : on suppose entre 5 000 et 200 000 raisonnable
df.loc[(df['Revenu'] < 5000) | (df['Revenu'] > 200000), 'Revenu'] = np.nan

# Pour Score : entre 0 et 100
df.loc[(df['Score'] < 0) | (df['Score'] > 100), 'Score'] = np.nan

# Pour Montant_Achat : pas de valeurs négatives
df.loc[df['Montant_Achat'] < 0, 'Montant_Achat'] = np.nan

Et on complète les éventuels *NaN* restants par la médiane :

In [ ]:
for col in ['Âge', 'Revenu', 'Score', 'Montant_Achat']:
    df[col].fillna(df[col].median(), inplace=True)

-   3. Correction et uniformisation des dates

Les dates sont dans plusieurs formats, voire invalides ('1988-13-45', '0000-00-00', etc.).

On force la conversion, puis on écarte les valeurs absurdes.

In [62]:
for col in ['Date_Naissance', 'Date_Inscription']:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Exclure les dates futures ou impossibles
today = pd.Timestamp.now()
df.loc[(df['Date_Naissance'] > today) | (df['Date_Naissance'].dt.year < 1900), 'Date_Naissance'] = np.nan

-   4. Vérifions le typage final

In [67]:
print("\n=== TYPES FINAUX ===")
print(df.dtypes)

print("\n=== EXTRAIT DE DONNÉES NUMÉRIQUES CORRIGÉES ===")
print(df[['Âge', 'Revenu', 'Score', 'Montant_Achat']].head(10))


""" 
Tu verras maintenant :

des nombres cohérents,
des montants sans symbole,
des dates converties ou remplacées par NaT si invalides.

"""

=== TYPES FINAUX ===
ID                           int64
Nom                            str
Âge                        float64
Genre                          str
Email                          str
Téléphone                      str
Ville                          str
Code_Postal                    str
Revenu                     float64
Date_Naissance      datetime64[us]
Date_Inscription    datetime64[us]
Statut                         str
Score                      float64
Commentaire                    str
Montant_Achat              float64
dtype: object

=== EXTRAIT DE DONNÉES NUMÉRIQUES CORRIGÉES ===
    Âge   Revenu  Score  Montant_Achat
0  25.0  50000.0   85.5        1500.50
1  30.0  60000.0   90.0        2000.00
2   NaN      NaN   78.3            NaN
3   NaN  55000.0    NaN        3000.00
4  28.0      NaN    NaN        2500.00
5   NaN  70000.0   88.8            NaN
6   NaN  65000.0    NaN        1800.75
7  42.0      NaN   92.1            NaN
8   0.0      NaN    NaN            NaN
9  35.0  72000.0   76.4        2200.00

' \nTu verras maintenant :\n\ndes nombres cohérents,\ndes montants sans symbole,\ndes dates converties ou remplacées par NaT si invalides.\n\n'

### 📊 Étape 5 : Détection et traitement des valeurs aberrantes (outliers)

Les outliers sont des valeurs numériques très éloignées du reste — parfois des erreurs, parfois de vrais cas rares.

On doit donc :

-   Les détecter,
-   Décider s’ils sont anormaux ou plausibles,
-   Soit les corriger, soit les supprimer.

1. Détection statistique basique

On commence avec la règle du IQR (Interquartile Range) :

On considère comme outliers les valeurs hors de l’intervalle :

[Q1 - 1.5 × IQR,  Q3 - 1.5 × IQR ]

In [ ]:
def detecter_outliers(colonne):
    Q1 = df[colonne].quantile(0.25)
    Q3 = df[colonne].quantile(0.75)
    IQR = Q3 - Q1
    borne_inf = Q1 - 1.5 * IQR
    borne_sup = Q3 + 1.5 * IQR
    outliers = df[(df[colonne] < borne_inf) | (df[colonne] > borne_sup)]
    print(f"\n{colonne}: {len(outliers)} valeurs aberrantes détectées")
    print(f"Borne inférieure: {borne_inf:.2f}, Borne supérieure: {borne_sup:.2f}")
    return outliers[[colonne]]

for col in ['Âge', 'Revenu', 'Score', 'Montant_Achat']:
    detecter_outliers(col)


# Ce code affiche le nombre et les bornes d’anomalies pour chaque variable numérique.

Âge: 2 valeurs aberrantes détectées
Borne inférieure: 16.00, Borne supérieure: 40.00

Revenu: 0 valeurs aberrantes détectées
Borne inférieure: 27500.00, Borne supérieure: 87500.00

Score: 0 valeurs aberrantes détectées
Borne inférieure: 66.55, Borne supérieure: 102.15

Montant_Achat: 1 valeurs aberrantes détectées
Borne inférieure: 676.41, Borne supérieure: 3074.16

-   2. Décision sur le traitement

In [ ]:
""" 
Colonne	                      Type d'anomalie	                                       Décision

Âge	                    Trop vieux (ex. >120) ou négatif (déjà corrigé)	                 OK
Revenu	                Extrêmement haut (ex. 999 999 999)	                   Supprimer ou remplacer par médiane
Score	                     >100 ou <0 (corrigé avant)	                                   OK
Montant_Achat	             Valeurs <0 ou déraisonnables	                    Corrigées à NaN puis remplacées

"""

Si l’on décide de **nettoyer automatiquement**, on peut « capper » les valeurs :

In [70]:
# capper les valeurs signifie que les valeurs extrêmes seront ramenées à la borne inférieure ou supérieure au lieu d'être supprimées.

def capper(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    borne_inf = Q1 - 1.5 * IQR
    borne_sup = Q3 + 1.5 * IQR
    df[col] = np.clip(df[col], borne_inf, borne_sup)

for col in ['Âge', 'Revenu', 'Score', 'Montant_Achat']:
    capper(df, col)


#  np.clip coupe les valeurs extrêmes aux bornes raisonnables, sans supprimer la ligne.

-    3. Vérification graphique optionnelle

Pour visualiser avant/après :

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
df[['Âge','Revenu','Score','Montant_Achat']].boxplot()
plt.title("Valeurs après correction des outliers")
plt.show()

# Tu devrais voir des boxplots beaucoup plus « ramassés » → les valeurs extrêmes ont été corrigées.

### 🧠 Étape 6 : Standardisation des catégories

**Objectif** : regrouper les valeurs équivalentes mais écrites différemment.

(C’est souvent négligé, mais c’est essentiel pour les analyses et regroupements corrects.)

-   1. Standardisation du Genre

On a des variantes comme :

['F', 'Femme', 'female', 'f', 'M', 'Male', 'H', 'Masculin', 'Inconnu', 'X', ...]

On va toutes ramener à un format clair :

-> ‘F’, ‘M’, ou ‘Inconnu’

In [72]:
# Dictionnaire de correspondances
genre_map = {
    'f': 'F', 'femme': 'F', 'female': 'F',
    'm': 'M', 'male': 'M', 'masculin': 'M', 'h': 'M', 'homme': 'M',
    'x': 'Inconnu', 'inconnu': 'Inconnu', 'autre': 'Inconnu', 'none': 'Inconnu'
}

df['Genre'] = df['Genre'].str.lower().map(genre_map).fillna('Inconnu')

-   2. Standardisation du Statut

Valeurs observées : ['Actif', 'actif ', 'Pending', 'Inactive', '1', '0', 'Oui', 'Non', 'Active', 'N/A', …]

→ On les convertit en 'Actif', 'Inactif', ou 'Autre'

In [73]:
statut_map = {
    'actif': 'Actif', 'active': 'Actif', 'oui': 'Actif', '1': 'Actif',
    'inactif': 'Inactif', 'inactive': 'Inactif', 'non': 'Inactif', '0': 'Inactif',
    'pending': 'Autre'
}

df['Statut'] = df['Statut'].str.lower().map(statut_map).fillna('Autre')

-   3. Standardisation de la Ville

Problèmes rencontrés :

-   Différences de casse : Paris / paris
-   Espaces, valeurs manquantes, ou 'Unknown'

In [ ]:
df['Ville'] = df['Ville'].str.strip().str.title()
df['Ville'].replace({'Unknown': np.nan, 'Inconnu': np.nan, 'Na': np.nan}, inplace=True)

On pourrait aussi regrouper les villes par catégories (régions, etc.) si utile plus tard.

-   4. Standardisation des emails invalides

Certaines entrées comme '*bob_email.com*', '*charlie@email*', ou '' ne sont pas valides.

On retire les emails invalides via une regex.

In [75]:
pattern_email_valide = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

df['Email_valide'] = df['Email'].apply(lambda x: bool(re.match(pattern_email_valide, str(x))) if pd.notna(x) else False)

Option : supprimer ou signaler les emails invalides :

In [77]:
df.loc[~df['Email_valide'], 'Email'] = np.nan  

# ~df['Email_valide'] sélectionne les lignes où l'email n'est pas valide, et on remplace ces emails par NaN.

-   5. Vérification rapide

In [ ]:
print(df[['Genre', 'Statut', 'Ville', 'Email']].head(10))

""" 
Tu verras maintenant :

des genres clairs (F, M, ou Inconnu),
des statuts uniformes (Actif, Inactif, Autre),
des villes bien formatées,
des emails nettoyés.

"""

     Genre   Statut      Ville            Email
0        F    Actif      Paris  alice@email.com
1        M    Actif      Paris              NaN
2        M  Inactif       Lyon              NaN
3        M    Autre       Lyon  DAVID@EMAIL.COM
4        F    Actif  Marseille    eve@email.com
5        M    Autre   Toulouse              NaN
6        F    Actif   Toulouse  grace@email.com
7  Inconnu  Inactif        NaN  henry@email.com
8  Inconnu    Actif        NaN              NaN
9        M    Autre   Bordeaux   jack@email.com

### 📞 Étape 7 : Nettoyage des formats spécifiques

Nous allons traiter les champs qui ont des formats particuliers :

→ numéros de téléphone, code postal, et montant déjà presque propre (mais à finaliser).

-   1. 📱 Téléphone

Problèmes observés :

-   Espaces, points, tirets
-   Formats mixtes +33, 0033, 06
-   Fausses valeurs ("abcdefghij", "0000000000", None…)

On veut obtenir un format unique du type : 0745513541

In [79]:
def nettoyer_telephone(tel):
    # si la valeur est déjà NaN, on la laisse telle quelle
    if pd.isna(tel):  
        return np.nan
    
    tel = str(tel) # convertir en string au cas où c'est un nombre
    tel = re.sub(r'\D', '', tel)  # supprime tout sauf chiffres

    # Retirer indicatifs internationaux +33 ou 0033
    if tel.startswith('33'):
        tel = '0' + tel[2:]
        
    elif tel.startswith('0033'):
        tel = '0' + tel[4:]
    # Valider longueur correcte
    if len(tel) != 10 or not tel.startswith('0'):
        return np.nan
    return tel

df['Téléphone'] = df['Téléphone'].apply(nettoyer_telephone)

-   2. 📮 Code postal

Problèmes :

-   Trop courts, lettres dedans ("6900A", "XXXXX")
-   Codes impossibles (‘-1’, '99999')

On garde uniquement des valeurs numériques à 5 chiffres raisonnables (01000–98000 en France par exemple).

In [80]:
def nettoyer_code_postal(cp):
    if pd.isna(cp):
        return np.nan
    cp = str(cp).strip()
    if not re.match(r'^\d{5}$', cp): # doit être exactement 5 chiffres
        return np.nan
    
    if not (1000 <= int(cp) <= 98000):  # les codes postaux français sont généralement entre 01000 et 98000
        return np.nan
    return cp

df['Code_Postal'] = df['Code_Postal'].apply(nettoyer_code_postal)

-   3. 💶 Montant d’achat finalisation

Tu avais déjà nettoyé cette colonne, mais pour uniformiser les décimales :

In [81]:
df['Montant_Achat'] = df['Montant_Achat'].round(2)

-   4. Validation rapide

In [83]:
print(df[['Téléphone', 'Code_Postal', 'Montant_Achat']].head(10))

# Tu devrais voir des numéros à 10 chiffres, codes postaux réalistes, et montants numériques nets.

    Téléphone Code_Postal  Montant_Achat
0  0612345678       75001        1500.50
1  0612345679       69001        2000.00
2  0612345680       13001            NaN
3         NaN       31000        3000.00
4         NaN       75002        2500.00
5         NaN       31001            NaN
6  0612345682         NaN        1800.75
7  0612345683         NaN            NaN
8  0000000000         NaN            NaN
9  0612345684       33000        2200.00

### 🧬 Étape 8 : Gestion des doublons

Les doublons sont des lignes identiques ou quasi identiques : mêmes individus répétés, mêmes identifiants, ou données saisies deux fois.

-   1. Identifier les lignes dupliquées

D’abord, on évalue combien de lignes exactes sont entièrement identiques :

In [89]:
doublons_entiers = df[df.duplicated()]
print(f"Doublons complets détectés : {doublons_entiers.shape[0]}")

# print(doublons_entiers)

Doublons complets détectés : 0

-   2. Supprimer les doublons stricts

In [ ]:
df.drop_duplicates(inplace=True)

# Cela garde la première occurrence et supprime les suivantes.

-   3. Détection des doublons « partiels » (mêmes ID, ou mêmes personnes)

On peut aussi vérifier les doublons par *ID*, *Nom*, ou *Email*, selon la logique métier.

In [91]:
# Doublons d'ID
doublons_id = df[df['ID'].duplicated(keep=False)].sort_values(by='ID')
print("\nDoublons potentiels par ID :")
print(doublons_id[['ID', 'Nom', 'Email', 'Ville']])

# Doublons de Nom + Email (cas de doublon humain probable)
doublons_personne = df[df.duplicated(subset=['Nom', 'Email'], keep=False)]
print("\nDoublons potentiels par Nom + Email :")
print(doublons_personne[['Nom', 'Email', 'Ville']])

Doublons potentiels par ID :
    ID      Nom          Email Ville
2    3  Charlie            NaN  Lyon
12   3      Mia  mia@email.com  Nice

Doublons potentiels par Nom + Email :
      Nom            Email  Ville
0   Alice  alice@email.com  Paris
10  Alice  alice@email.com  Paris

-   4. Traitement recommandé

In [92]:
""" 
Cas                                  	                                             Action

ID répétés avec même contenu	                                            Supprimer les doublons
ID répétés mais avec différences mineures	             Conserver la version la plus complète (plus de données non NaN)
Doublon humain (Nom + Email)	                                      Fusionner les enregistrements

"""

' \nCas                                  \t                                             Action\n\nID répétés avec même contenu\t                                            Supprimer les doublons\nID répétés mais avec différences mineures\t             Conserver la version la plus complète (plus de données non NaN)\nDoublon humain (Nom + Email)\t                                      Fusionner les enregistrements\n\n'

Voici comment garder la ligne avec le plus de données renseignées :

In [97]:
df = df.sort_values(by=['ID'])

# Supprimer les lignes où 'Nom' est NaN, puis faire idxmax
df = df.dropna(subset=['Nom'])
df = df.loc[df.groupby('ID')['Nom'].idxmax()]    # ou toute autre stratégie selon le cas

# idmax : pour chaque groupe d'ID, on garde la ligne où le nom est "maximal" (ex. le plus complet).
# exemple : si on a deux lignes avec ID=3, l'une avec Nom='Charlie' et l'autre avec Nom='Mia', 
#  on gardera celle avec 'Mia' car 'Mia' > 'Charlie' en ordre alphabétique.

df.head()

,ID,Nom,Âge,Genre,Email,Téléphone,Ville,Code_Postal,Revenu,Date_Naissance,Date_Inscription,Statut,Score,Commentaire,Montant_Achat,Email_valide
0,1,Alice,25.0,F,alice@email.com,0612345678,Paris,75001,50000.0,1998-05-15,2020-01-15,Actif,85.5,RAS,1500.50,True
1,2,Bob,30.0,M,NaN,0612345679,Paris,69001,60000.0,NaT,2020-01-15,Actif,90.0,NaN,2000.00,False
12,3,Mia,29.0,F,mia@email.com,0612345685,Nice,06000,48000.0,1994-11-30,2021-04-18,Inactif,81.2,Satisfait,1950.25,True
3,4,David,NaN,M,DAVID@EMAIL.COM,NaN,Lyon,31000,55000.0,NaT,2021-03-10,Autre,NaN,NaN,3000.00,True
4,5,Eve,28.0,F,eve@email.com,NaN,Marseille,75002,NaN,NaT,2018-12-01,Actif,NaN,Client fidèle depuis 5 ans!!!,2500.00,True

-   5. Vérification finale

In [100]:
print(f"Nombre final de lignes : {df.shape[0]}")
print(f"Nombre d'ID uniques : {df['ID'].nunique()}")

Nombre final de lignes : 12
Nombre d'ID uniques : 12

### ✅ Étape 9 : Vérification finale du DataFrame propre

On va vérifier que :

-   il ne reste plus d’anomalies visibles,
-   les types sont corrects,
-   les valeurs sont cohérentes,
-   et notre DataFrame est prêt pour l’analyse ou l’entraînement d’un modèle.

-   1. Vérification globale des types

In [101]:
print("=== TYPES DE DONNÉES ===")
print(df.dtypes)

=== TYPES DE DONNÉES ===
ID                           int64
Nom                            str
Âge                        float64
Genre                          str
Email                          str
Téléphone                      str
Ville                          str
Code_Postal                    str
Revenu                     float64
Date_Naissance      datetime64[us]
Date_Inscription    datetime64[us]
Statut                         str
Score                      float64
Commentaire                    str
Montant_Achat              float64
Email_valide                  bool
dtype: object

-   2. Vérification des valeurs manquantes résiduelles

In [102]:
print("\n=== VALEURS MANQUANTES RESTANTES ===")
print(df.isna().sum().sort_values(ascending=False))

=== VALEURS MANQUANTES RESTANTES ===
Date_Naissance      8
Âge                 5
Score               5
Commentaire         5
Téléphone           4
Email               4
Revenu              3
Code_Postal         3
Montant_Achat       2
Ville               2
Genre               0
ID                  0
Nom                 0
Date_Inscription    0
Statut              0
Email_valide        0
dtype: int64

-> Il est normal qu’il reste quelques NaN (par ex. Date_Naissance invalides ou Email manquant).

Mais plus de volumes massifs comme au départ.

-   3. Contrôle des valeurs uniques et consistantes

In [ ]:
print("\n=== DIVERS RÉCAP ===")
print(f"Nombre total de lignes : {df.shape[0]}")
print(f"Nombres d'ID uniques : {df['ID'].nunique()}")
print(f"Genres : {df['Genre'].unique()}")
print(f"Statuts : {df['Statut'].unique()}")
print(f"Villes uniques : {df['Ville'].nunique()}")

# Ces infos te montrent que les catégories ont bien été normalisées (Genre : F/M/Inconnu, etc.).

=== DIVERS RÉCAP ===
Nombre total de lignes : 12
Nombres d'ID uniques : 12
Genres : <StringArray>
['F', 'M', 'Inconnu']
Length: 3, dtype: str
Statuts : <StringArray>
['Actif', 'Inactif', 'Autre']
Length: 3, dtype: str
Villes uniques : 7

-   4. Vérification statistique rapide

In [105]:
print("\n=== STATISTIQUES NUMÉRIQUES ===")
print(df[['Âge', 'Revenu', 'Score', 'Montant_Achat']].describe())

=== STATISTIQUES NUMÉRIQUES ===
             Âge        Revenu      Score  Montant_Achat
count   7.000000      9.000000   7.000000      10.000000
mean   26.857143  59111.111111  83.900000    1922.841000
std     5.871643   8908.485343   4.930855     626.589667
min    16.000000  48000.000000  76.400000     676.410000
25%    25.000000  50000.000000  80.550000    1575.562500
50%    28.000000  60000.000000  85.500000    1975.125000
75%    29.500000  65000.000000  87.150000    2175.000000
max    35.000000  72000.000000  90.000000    3000.000000

Permet de confirmer :

-   plus de valeurs absurdes (négatives, gigantesques, etc.),
-   des médianes/plages logiques.

-   5. Visualisation de cohérence optionnelle

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(df[['Âge', 'Revenu', 'Score', 'Montant_Achat']])
plt.show()


# Les plots devraient afficher des distributions raisonnables (pas de points aberrants extrêmes).

-   6. Sauvegarde du DataFrame final propre

In [108]:
# Sauver le DataFrame nettoyé dans un nouveau fichier CSV dans le dossier assets
df.to_csv('assets/clients_nettoyes.csv', index=False)

Oui, notre jeu de données est maintenant propre et prêt à être utilisé pour du Machine Learning ou d’autres analyses — 

mais il reste deux réflexes avant le modelling :

-   ⚙️ 1. Les *NaN* et *NaT* restants

Ils ne sont pas un problème en soi tant qu’ils sont :

-   rares,
-   contrôlés,
-   et traités consciemment selon la colonne.

En pratique :

In [ ]:
""" 
Type de colonne                                                           	Gestion recommandée

Numérique (Âge, Revenu, Score, etc.)	         Remplacer les NaN par la moyenne, médiane, ou une valeur spéciale (0 ou -1) selon ton modèle
Catégoriel (Genre, Ville, Statut)	                              Les convertir en 'Inconnu' (catégorie explicite)
Date (Date_Naissance, Date_Inscription)	       Garder NaT (les modèles savent rarement traiter les dates brutes — on calculera plutôt l'âge, l'ancienneté, etc.)

"""

👉 *Scikit-learn* ne supporte pas directement les *NaN* : il faudra donc les imputer avant le *fit*.

Exemple rapide d’imputation :

In [110]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')  
# ou strategy='mean' selon ce qui est plus pertinent pour tes données, mais la médiane est souvent plus robuste aux outliers.

df[['Âge', 'Revenu', 'Score', 'Montant_Achat']] = imputer.fit_transform(df[['Âge', 'Revenu', 'Score', 'Montant_Achat']])

-   🧮 2. Préparation avant Machine Learning

Pour passer au ML, on doit :

-   Encoder les colonnes catégorielles (ex. Genre, Ville, Statut)
-   Créer des features utiles à partir des dates (ancienneté_client, âge_client, etc.)
-   Normaliser ou standardiser tes variables numériques
-   Diviser ton dataset en train/test

Exemple de pipeline minimal :

In [121]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# 1. Définition des colonnes
cat_cols = ['Genre', 'Ville']
num_cols = ['Âge', 'Revenu', 'Score', 'Montant_Achat']

# 2. Création des sous-pipelines (Bonne pratique pour la clarté)
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # Gère les valeurs manquantes
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False)) # sparse=False facilite parfois la visualisation
])

# 3. Assemblage du préprocesseur
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_cols),  # standardisation des numériques 
        ('cat', cat_transformer, cat_cols)   # encodage des catégorielles 
        ]
)


# 4. Pipeline final
clf = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('model', LogisticRegression(max_iter=1000, random_state=42))
])

# 5. Séparation et Entraînement : Variables explicatives et cible (exemple : prédire Statut)
X = df[num_cols + cat_cols]
y = df['Statut']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf.fit(X_train, y_train)

# 6. Évaluation complète
y_pred = clf.predict(X_test)

print("--- Rapport de Classification ---")
print(classification_report(y_test, y_pred))

--- Rapport de Classification ---
              precision    recall  f1-score   support

       Actif       1.00      1.00      1.00         3

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

In [ ]:
# Matrice de confusion

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Prédiction')
plt.ylabel('Réalité')
plt.show()

## ________________________________________________________________________________________

## Un petit resumé

### Concernant le traitement des NaN et autres ...

In [61]:
import pandas as pd
import numpy as np

data = {
    'ID client': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 3, 14, 15],  # Doublon d'ID
    'Nom': ['alice', 'BOB', 'Charlie', 'OsCAR', 'Eve', 'Frank', 'Grace', 'Harry', 'Alice', 'jack', 'kate', 'Lily', 'Mia', 'Nina', 'Oscar'],
    'Âge': [25, 30, 35, 40, 45, 50, 55, np.nan, 65, 70, 75, 80, 85, 90, 95],   
    'Genre': ['F', 'M', 'Masculin', 'H', 'Femme', 'M', 'f', None, 'X', 'M', 'F', 'Male', 'F', 'Inconnu', 'F'],
    'PROFESSION': ['Ingénieur', 'Médecin', 'Artiste', 'Avocat', 'Enseignant', 'Scientifique', 'Ingénieur', 'Inconnu', 'Médecin', 'Musicien', 'Architecte', 'Journaliste', 'Designer', 'Scientifique', 'Chef'],
    'Revenu': [50000, None, 55000, 70000, 65000, 60000, 72000, 48000, 62000, 58000, 54000, None, 59000, 63000, 68000],
    'ville': [np.nan, 'paris', None, 'Lyon ', ' Marseille', 'Toulouse', 'toulouse', None, 'N/A', 'Bordeaux', 'Paris', '', 'Nice', 'Unknown', 'Lille'],
    'Email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', 'dave@email.com', 'eve@email.com', np.nan, 'grace@email.com', 'harry@email.com', 'ivy@email.com', 'jack@email.com', 'kate@email.com', 'lily@email.com', 'mia@email.com', 'nina@email.com', 'oscar@email.com']
}


df = pd.DataFrame(data)
print(df.shape)
df.head()

(15, 8)

,ID client,Nom,Âge,Genre,PROFESSION,Revenu,ville,Email
0,1,alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,BOB,30.0,M,Médecin,NaN,paris,bob@email.com
2,3,Charlie,35.0,Masculin,Artiste,55000.0,None,charlie@email.com
3,4,OsCAR,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com

-   **Structuration et standardisation des colonnes**

Des noms de colonnes propres rendent le code lisible et évitent les bugs.

In [64]:
df.columns = (
    df.columns
    .str.lower()              
    .str.strip()                
    .str.replace(" ", "_")     
    .str.replace(r"[éèê]", "e", regex=True)  # supprimer accents
    .str.replace(r"[âà]", "a", regex=True)  # supprimer l'accent chapeau de l'Âge
)

df.head()

,id_client,nom,age,genre,profession,revenu,ville,email
0,1,alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,BOB,30.0,M,Médecin,NaN,paris,bob@email.com
2,3,Charlie,35.0,Masculin,Artiste,55000.0,None,charlie@email.com
3,4,OsCAR,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com

-   **1 - Gestion avancée des valeurs manquantes**


Stratégies de traitement


### Suppresion

In [65]:
# 1 - Suppression
# df.dropna(axis=0, inplace=True)  # axis=0 pour supprimer des lignes, axis=1 pour supprimer des colonnes
# df.dropna(axis=1, inplace=True)   

print(df.shape)
df.head()

(15, 8)

,id_client,nom,age,genre,profession,revenu,ville,email
0,1,alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,BOB,30.0,M,Médecin,NaN,paris,bob@email.com
2,3,Charlie,35.0,Masculin,Artiste,55000.0,None,charlie@email.com
3,4,OsCAR,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com

###  Imputation simple (moyenne, médiane, mode, constante)

In [33]:
# Pour une variable numérique : moyenne ou médiane (plus robuste)
# df["revenu"] = df["revenu"].fillna(df["revenu"].median())  

# Pour une variable catégorielle : mode ou "Inconnu"
# df["ville"] = df["ville"].fillna("Inconnu")

df.head()

,ID,Nom,Âge,Genre,profession,revenu,ville,Email
0,1,Alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,Bob,30.0,M,Médecin,NaN,paris,bob@email.com
2,3,Charlie,35.0,Masculin,Artiste,55000.0,None,charlie@email.com
3,4,Dave,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com

### Imputation avancée (logique métier ou groupée)

In [66]:
# Imputer le revenu par la moyenne du revenu selon la profession

"""
df["revenu"] = df.groupby("profession")["revenu"].transform(
    lambda x: x.fillna(x.mean())
)  """

df.head()

# ✅ Très utilisé en économétrie et analyse sociale : on suppose que le revenu dépend de la profession.

,id_client,nom,age,genre,profession,revenu,ville,email
0,1,alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,BOB,30.0,M,Médecin,NaN,paris,bob@email.com
2,3,Charlie,35.0,Masculin,Artiste,55000.0,None,charlie@email.com
3,4,OsCAR,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com

###  Interpolation (séries temporelles)

In [67]:
# Pour une série temporelle régulière
# df["valeur"] = df["valeur"].interpolate(method="linear")

# ✅ Idéal pour des données de capteurs ou financières.

-   **2 - Gestion des doublons**

Les doublons peuvent fausser les statistiques (surtout les moyennes) et surreprésenter certains individus.

### Détection

In [68]:
df.duplicated().sum()                # nombre total de lignes dupliquées

np.int64(0)

In [72]:
df.duplicated(subset=["id_client"]).sum()  # doublons sur une colonne clé

np.int64(0)

### Traitement

In [73]:
# Supprimer les doublons sur toutes les colonnes
df.drop_duplicates(inplace=True)

# Supprimer en gardant la dernière occurrence (la plus récente)
df.drop_duplicates(subset=["id_client"], keep="last", inplace=True)
print(df.shape)
df.head()

(14, 8)

,id_client,nom,age,genre,profession,revenu,ville,email
0,1,alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,BOB,30.0,M,Médecin,NaN,paris,bob@email.com
3,4,OsCAR,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com
5,6,Frank,50.0,M,Scientifique,60000.0,Toulouse,NaN

-   **3- Nettoyage et normalisation des variables textuelles**

Les chaînes de caractères contiennent souvent des espaces inutiles, des majuscules/minuscules incohérentes, des caractères spéciaux.

### Nettoyage typique

In [75]:
df["nom"] = (
    df["nom"]
    .str.title()                     # tout en majuscule au début de chaque mot
    .str.strip()                     # supprime espaces début/fin
    .str.replace(r"[^\w\s]", "", regex=True)  # supprime ponctuation
)

df.head()

,id_client,nom,age,genre,profession,revenu,ville,email
0,1,Alice,25.0,F,Ingénieur,50000.0,NaN,alice@email.com
1,2,Bob,30.0,M,Médecin,NaN,paris,bob@email.com
3,4,Oscar,40.0,H,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Femme,Enseignant,65000.0,Marseille,eve@email.com
5,6,Frank,50.0,M,Scientifique,60000.0,Toulouse,NaN

-   **4 - Gestion des catégories incohérentes**

In [76]:
df["genre"] = df["genre"].replace({
    "M": "Masculin",
    "m": "Masculin",
    "F": "Féminin",
    "f": "Féminin",
    "H": "Masculin",   # si le codage utilise H/F
    "Femme": "Féminin"
})

df.head()

,id_client,nom,age,genre,profession,revenu,ville,email
0,1,Alice,25.0,Féminin,Ingénieur,50000.0,NaN,alice@email.com
1,2,Bob,30.0,Masculin,Médecin,NaN,paris,bob@email.com
3,4,Oscar,40.0,Masculin,Avocat,70000.0,Lyon,dave@email.com
4,5,Eve,45.0,Féminin,Enseignant,65000.0,Marseille,eve@email.com
5,6,Frank,50.0,Masculin,Scientifique,60000.0,Toulouse,NaN

-   **5 - Gestion des valeurs uniques et cardinalité**

Analyser les valeurs uniques aide à repérer des erreurs de saisie ou des niveaux de granularité trop fins.

In [79]:
df["profession"].nunique()          # nombre de valeurs distinctes
df["profession"].value_counts()     # distribution détaillée

profession
Ingénieur       2
Médecin         2
Scientifique    2
Avocat          1
Enseignant      1
Inconnu         1
Musicien        1
Architecte      1
Journaliste     1
Designer        1
Chef            1
Name: count, dtype: int64

## Remerciements

Un grand merci d'être allé jusqu'au bout de ce notebook ! 🙏

Nettoyer des données n'est peut-être pas la tâche la plus glamour de la data science, mais c'est sans doute la plus essentielle.

En prenant le temps de maîtriser ces bonnes pratiques avec Pandas, vous venez de poser les bases les plus solides qui soient pour toutes vos analyses futures : des données fiables, compréhensibles et prêtes à être modélisées.

J'espère que ces exemples concrets et cette méthodologie vous accompagneront dans vos projets, qu'il s'agisse du data science, d'économétrie, de suivi-évaluation ou de machine learning.

Si ce contenu vous a été utile, n'hésitez pas à le partager autour de vous. Et surtout : **ne faites jamais confiance à des données brutes sans les avoir explorées et nettoyées vous-même 😉**


Bon courage pour la suite, et que vos données soient toujours propres !

**À très bientôt pour de nouveaux apprentissages.**

💡 FOFANA Lamine